{
 "title": "BMS",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Battery Voltage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  ts AS \"time\",\n  volts\nFROM bms\nWHERE\n  $__timeFilter(ts)\nORDER BY ts"
    }
   ]
  },
  {
   "title": "Power",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  ts AS \"time\",\n  watts,\n  amps\nFROM bms\nWHERE\n  $__timeFilter(ts)\nORDER BY ts"
    }
   ]
  },
  {
   "title": "Cell Voltages",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  ts AS \"time\",\n  cv1,\n  cv2,\n  cv3,\n  cv4,\n  cv5,\n  cv6,\n  cv7,\n  cv8,\n  cv9,\n  cv10,\n  cv11,\n  cv12,\n  cv13,\n  cv14,\n  cv15,\n  cv16\nFROM bms\nWHERE\n  $__timeFilter(ts)\nORDER BY ts"
    }
   ]
  },
  {
   "title": "Remaining",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "amph" } },
   "yaxes": [
    { "format": "amph" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  ts AS \"time\",\n  remaining\nFROM bms\nWHERE\n  $__timeFilter(ts)\nORDER BY ts"
    }
   ]
  },
  {
   "title": "SOC",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  ts AS \"time\",\n  percent\nFROM bms\nWHERE\n  $__timeFilter(ts)\nORDER BY ts"
    }
   ]
  },
  {
   "title": "Info",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 16, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  ts AS \"time\",\n  cycles,\n  temp1,\n  temp2,\n  temp3\nFROM bms\nWHERE\n  $__timeFilter(ts)\nORDER BY ts"
    }
   ]
  },
  {
   "title": "Cells Graph",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  ts AS \"time\",\n  cv1,\n  cv2,\n  cv3,\n  cv4,\n  cv5,\n  cv6,\n  cv7,\n  cv8,\n  cv9,\n  cv10,\n  cv11,\n  cv12,\n  cv13,\n  cv14,\n  cv15,\n  cv16\nFROM bms\nWHERE\n  $__timeFilter(ts)\nORDER BY ts"
    }
   ]
  }
 ]
}